### ISSUE TITLE
Mio Cloud seems not to work :(

### ISSUE THREAD

**Issue by titidnh** [maxinminax/node-mihome#1]
Hi,

When i try to call login method i receive an exception ..

 node Test.js 
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

const mihome = require('node-mihome');

async function LoginMethod()
{
  await mihome.miCloudProtocol.login({
    username: 'xxxx',
    password: 'xxxx'
  });
}

LoginMethod().catch(err => console.log(err.message));

**Comment by maxinminax** [comment]
I have mistake when write the document:
Pls try with: 
`mihome.miCloudProtocol.login(username, password)`
