### ISSUE TITLE
Possible Errors in Readme

### ISSUE THREAD

**Issue by Pittini** [maxinminax/node-mihome#12]
Hi, i think there are three little but disgusting errors in the readme and Examples.

1. This Link is dead:
http://docs.opencloud.aqara.com/en/development/gateway-LAN-communication/

2. This Line drops errors, but works without the "s", so i think its a copy&paste error:
Doesnt work:
`await mihome.miCloudProtocol.getDevices([deviceId1, deviceId2, ...], options); // get devices information from list ids`

This works:
`await mihome.miCloudProtocol.getDevice([deviceId1, deviceId2, ...], options); // get devices information from list ids`

3. This code drops errors, but works if i change parent to data:
Doesnt work:
```
device.on('properties', (data) => {
  console.log(properties);
});
```
This works:
```
device.on('properties', (data) => {
  console.log(data);
});
```

**Comment by maxinminax** [comment]
It was fixed

**Comment by Pittini** [comment]
> It was fixed

Sorry, but at this time not one of three Errors is fixed.
