### ISSUE TITLE
New Device hhcc.plantmonitor.v1 (Flower Care)

### ISSUE THREAD

**Issue by Pittini** [maxinminax/node-mihome#25]
Hi please insert the Device for testing. I own one.
https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:plant-monitor:0000A030:hhcc-v1:1

It's this device:
https://www.banggood.com/de/Global-Version-Flora-4-In-1-Flower-Plant-Light-Temperature-Tester-Garden-Soil-Moisture-Nutrient-Monitor-p-1068369.html?cur_warehouse=CN

**Comment by maxinminax** [comment]
This device can't connect to wifi, it use bluetooth and has other protocol. I'm working hard to provide new protocol base on xiaomi bluetooth device, may you just wait
