### ISSUE TITLE
mioCall on country de ?

### ISSUE THREAD

**Issue by titidnh** [maxinminax/node-mihome#3]
Are you sure your code works with other countries ? It seems i've some issues because the miocall is made on CN but i used the getDevice on "DE"

**Comment by maxinminax** [comment]
> Are you sure your code works with other countries ? It seems i've some issues because the miocall is made on CN but i used the getDevice on "DE"

I have update to new version 0.0.22 which will support other countries. Please update and flow the document:

```javascript
const options = { country: 'cn' }; // 'ru', 'us', 'tw', 'sg', 'cn', 'de' (Default: 'cn')
await mihome.miCloudProtocol.getDevices(null, options); // return all devices from your acount with all information (deviceId, token, model ...) to create device in the next step
await mihome.miCloudProtocol.getDevices([deviceId1, deviceId2, ...], options); // get devices information from list ids
await mihome.miCloudProtocol.miiCall(deviceId, method, params, options); // call miio method with params via cloud protocol```

**Comment by beshkin** [comment]
Hi,

getting the following error:
`(node:57995) UnhandledPromiseRejectionWarning: FetchError: network timeout at: https://de.api.io.mi.com/app/home/rpc/374335513
    at Timeout.<anonymous> (/home/misha/workspace/automation-server/node_modules/node-fetch/lib/index.js:1454:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
`
Devices list working just fine.
If you need more information from, I would be happy to assist.
