### ISSUE TITLE
Changed login prozedure leads to: Error: Request error with status Unauthorized

### ISSUE THREAD

**Issue by Pittini** [maxinminax/node-mihome#45]
Since yesterday login is no more possible. It seems like Xiaomi has changed something to the login procedure. This is an urgency, pls fix as soon as possible.

See also: https://github.com/Pittini/iobroker-nodemihome/issues/56

Addition: Seem to be only at EU Servers

**Comment by Siggi0904** [comment]
There is an adaption from py ty js from https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/blob/master/token_extractor.py needed.

**Comment by Pittini** [comment]
Seems to be fixed by Xiaomi. Now again working as usual.

**Comment by Siggi0904** [comment]
Should be changed in addition to the old access mode. Or a second way should be implemented.
