### ISSUE TITLE
Convert to TypeScript?

### ISSUE THREAD

**Issue by 0x2206** [maxinminax/node-mihome#7]
First of all thanks for this lib! That's really awesome we have alternative to, probably abandoned, https://github.com/aholstenson/miio.

I played with node-mihome lib for a while and it looks really promising. I achieved what was not possible with @aholstenson/miio in several lines of code. Cool :-)

What do you think about moving to TypeScript for development? I can help with this. Do you accept PRs?

**Comment by maxinminax** [comment]
Thankyou and welcome for all PRs

**Comment by ouv27** [comment]
Hello, is it possible to use miio library in TypeScript development ?
A working js code didn't work in TypeScript with this error : (node:8212) UnhandledPromiseRejectionWarning: TypeError: fetch is not a function at MiCloudProtocol._loginStep1 
An idea ? Tks a lot for your help
